name: 03 - Workflow Runners
on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
       - name: show os
         run: |
           echo "This job is running on a ubuntu runner"
           echo "Runner OS: $RUNNER_OS"
#   window-echo:
#     runs-on: windows-latest
#     shell: bash
#     steps:
#       - name: Show os
#         run: |
#           echo "This job runs on Windows runner"
#           echo " ${{}}"
#    mac-echo:
#     runs-on: macos-latest
#     steps:
#       - name: Show os
#         run: |
#            echo "Thisn job is running on Mac os runner"

    

