name: 04-Using action
on: push

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v4
       - name: Setup the node
         uses: action/setup-node@v4
         with:
            node-version: '20.x'
       - name: Intall the dependencies
         run: npm ci
       - name: Printing folder
         run: ls
         