name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: ${{matrix.os}}-${{matrix.node-version}}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            node-version: [18.x, 20.x,21.x]
            os:
              - ubuntu-latest
              - window-latest
            include:
              - os: ubuntu-latest
                node-version: 15.x
    steps:
       - name: setup-node
         uses: actions/setup-node@v3
         with: 
          node-version: ${{matrix.node-version}}

       - name: Perform some test
         run: echo "Running tests on os ${{matrix.os }} and node js ${{matrix.node-version}}"

  inlcude-example:
    runs-on: ubuntu-latest
    name: ${{ matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include: 
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          - color: red
            shape: triagle
            opacity: 50
        exclude:
          - opacity: 75

    steps:
      - name: Dummy step
        run: echo "${{ matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}"
        

     
     